### PR TITLE
Update superagent to 3.4

### PR DESCRIPTION
**Pull request by ktonon**

### CODE REVIEW

**Comment by ktonon** [comment]
@omsmith does this look good? I have to wait for this to get published so I can submit PRs to the other repos which depend on it

**Comment by omsmith** [comment]
Was waiting for a PR for frau-jwt still, https://github.com/Brightspace/frau-jwt/blob/master/package.json#L47

**Comment by ktonon** [comment]
Sorry, I need some clarification. This is the dependency graph right?
deps

I figured since this repo (`frau-xsrf-token`) does not depend on the others, I should update this one first.

In order to update `frau-superagent-xsrf-token`, I need to have a published npm package for `frau-xsrf-token` (I assume version `2.0.0`)

**Comment by omsmith** [comment]
Ah quite, wasn't thinking of the version bumps between packages. Sorry!

**Comment by ktonon** [comment]
awesome, thanks!

**Pull request merged**
